# Generated by Django 3.2 on 2021-05-22 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210522_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=111),
            preserve_default=False,
        ),
    ]
